# Generated by Django 6.0.4 on 2026-04-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("pressure", models.FloatField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="device_identity.device",
                    ),
                ),
            ],
        ),
    ]
