# Generated by Django 6.0.4 on 2026-04-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_identity", "0002_devicemeasurement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="token",
        ),
        migrations.AddField(
            model_name="device",
            name="token_hash",
            field=models.CharField(default="deleted", max_length=256),
            preserve_default=False,
        ),
    ]
