# Generated by Django 6.0.4 on 2026-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_identity', '0003_remove_device_token_device_token_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemeasurement',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='devicemeasurement',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='devicemeasurement',
            name='temperature',
        ),
        migrations.AddField(
            model_name='device',
            name='schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='devicemeasurement',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
